info:
  component: zuul server app  
server: 
  port: 2020
spring:
  config:
    name: zuul
  application:
    name: ZuulServer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/      
zuul:
  routes:
    student-service:
      path: /student-api/**
      service-id: STUDENT-SERVICE
    class-service:
      path: /class-api/**  
      service-id: CLASS-SERVICE    
  ribbon-isolation-strategy: THREAD 
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 2000
       
